# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(10, 180, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_next.setFont(font)
        self.btn_next.setObjectName("btn_next")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(10, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.lbl_video = QtWidgets.QLabel(self.centralwidget)
        self.lbl_video.setGeometry(QtCore.QRect(110, 50, 491, 391))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_video.setFont(font)
        self.lbl_video.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_video.setText("")
        self.lbl_video.setObjectName("lbl_video")
        self.lbl_bienso = QtWidgets.QLabel(self.centralwidget)
        self.lbl_bienso.setGeometry(QtCore.QRect(600, 50, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_bienso.setFont(font)
        self.lbl_bienso.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_bienso.setText("")
        self.lbl_bienso.setObjectName("lbl_bienso")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(10, 120, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_play.setFont(font)
        self.btn_play.setObjectName("btn_play")
        self.led_model = QtWidgets.QLineEdit(self.centralwidget)
        self.led_model.setGeometry(QtCore.QRect(110, 10, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.led_model.setFont(font)
        self.led_model.setObjectName("led_model")
        self.btn_init = QtWidgets.QPushButton(self.centralwidget)
        self.btn_init.setGeometry(QtCore.QRect(10, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_init.setFont(font)
        self.btn_init.setObjectName("btn_init")
        self.btn_open_model = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_model.setGeometry(QtCore.QRect(790, 0, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_open_model.setFont(font)
        self.btn_open_model.setObjectName("btn_open_model")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_next.setText(_translate("MainWindow", "Next"))
        self.btn_load.setText(_translate("MainWindow", "Load"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.led_model.setText(_translate("MainWindow", "D:\\9.ATC_AI_Core\\YOLO_Trainers\\BIENSOXE\\runs\\detect\\train_detectbienso\\weights\\best.pt"))
        self.btn_init.setText(_translate("MainWindow", "Init"))
        self.btn_open_model.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
